# Generated by Django 4.2.3 on 2023-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='password',
            field=models.CharField(default='Password@123', max_length=15),
        ),
    ]
